name = "ThesisSimulations"
uuid = "35840eb9-573c-4b08-aec0-97a4171fc477"
authors = ["Stephan Scholz"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
